### ISSUE TITLE
Connect Sonaria.com to WPengine

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#1]
To connect sonaria.com from BlueHost to WPengine, the DNS information will need to be updated to point to the CNAME sonaria.wpengine.com or the IP Address 104.154.168.186.

**Comment by d4mation** [comment]
Once done, please let me know so that I can get the necessary things set within the Database :+1:

**Comment by TheMarketingGuy** [comment]
DNS changes in BlueHost complete directing to WPengine.

[RE_ sonaria.com DNS Migration.pdf](https://github.com/lowrysolutions/sonaria-theme-2018/files/1686119/RE_.sonaria.com.DNS.Migration.pdf)

**Comment by TheMarketingGuy** [comment]
Implement SSL for Sonaria.com

**Comment by d4mation** [comment]
SSL cert is pending: https://my.wpengine.com/installs/sonaria/ssl_certificates

Once that finalizes, it will be all set. I've already done the search/replace on the database for it, so in the meantime the site may should warnings about being insecure. This is expected behavior and will go away once the SSL cert is fully in place.

**Comment by d4mation** [comment]
New IP Address is now `104.197.142.114`. When upgrading to PHP 7 as part of #2 it changed.

**Comment by TheMarketingGuy** [comment]
So...are we all set now with this?

1. DNS change complete
2. SSL set
3. Upgraded to PHP 7

**Comment by d4mation** [comment]
No, the DNS needs updated again as the IP Address changed when PHP 7 was implemented. 

It needs to be changed to `104.197.142.114`

**Comment by TheMarketingGuy** [comment]
@nikdagostino - please see the above comments. 

Could you please facilitate the change?

**Comment by nikdagostino** [comment]
I've changed the DNS to point to 104.197.142.114. Just time to propagate and it will be all set.
