### ISSUE TITLE
Sonria Stage

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#10]
Please create a Sonaria staging area.

**Comment by BigActual** [comment]
@d4mation - Can this ticket be closed?

**Comment by d4mation** [comment]
Done. @TheMarketingGuy, copying from Live->Staging can be done from this menu:

![image](https://user-images.githubusercontent.com/7770631/38495436-93340816-3bc7-11e8-9f9d-afc7d1c2bc8c.png)
