### ISSUE TITLE
Sonaria Post Feature Image

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#11]
I've created a post for the announcement of Sonaria that **MUST** go live at 10:00 AM on  Monday, April 9, but don't know the feature image dimensions. 

I uploaded the standard feature image size of 900 x 400 used in lowrysolutions.com, but it is obviously not working.

Not sure which would be best...make the 900 x 400 work, insert the media in the post above the text, or create a new image based on the dimensions you tell me. In all honesty, I'm not sure if I'll have time to create a new one.

**Comment by d4mation** [comment]
On my screen, the image container renders at `1440x400`. You shouldn't need to have an image at that exact size, but one with a width-to-height ratio of 18:5 would fit best. 

If you don't have time to recreate the image, you could remove the featured image and instead place it in the content editor like you said. That may not look as nice, but it would prevent the image from being cut off in the featured image container.

**Comment by BigActual** [comment]
@TheMarketingGuy - If this is helpful, let us know by closing the issue when the image is implemented.

**Comment by TheMarketingGuy** [comment]
OK to close!
