### ISSUE TITLE
Shortcodes or similar solution

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#12]
We don't have content to build a "menu" yet but I need to at least add 2 CTAs to the Sonaria splash/home page **by 10:00 AM, Monday, April 9.**

1 for a webinar registration and 1 for a "Press Room" (a.k.a. blog posts/press releases).

My plan is to take care of that with 2 buttons for now. I do not see any functionality for buttons in the editor. I could html code them in if you don't have a handy shortcode plugin that could be loaded in.

**Comment by d4mation** [comment]
This can be tested on http://sonaria.staging.wpengine.com/ using the `issue/12/button-shortcode` branch. You can switch branches under Appearance->Themes

![image](https://user-images.githubusercontent.com/7770631/38496301-0562fd36-3bcb-11e8-9d4c-46752f4c0c51.png)

**Comment by TheMarketingGuy** [comment]
I didn't even catch this until just now. I ended up just dropping in button images.

Ok to close.
