### ISSUE TITLE
Sonaria Page Attributes

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#13]
I'm sorry to ask this...but I guess I'm way to accustomed to constructing with a builder. 

Could you provide some info on the available page attributes?

To me the Sonaria splash page looks odd. I tried setting it to Full Width, but it still seems to be rendering at 2/3 with a 1/3 blank space to the right.

**Comment by d4mation** [comment]
That is the full-width template. You're thinking more of a "full-bleed", but "full-width" just means no sidebars.

**Comment by d4mation** [comment]
Actually, re-read this and something is wrong with this. I'll take a look

**Comment by d4mation** [comment]
Should be set now. You may need to hard-refresh your browser. 

Just a heads up: The Page Template selector does not do anything for the Home Page. Normally I disable that option for the Home Page to prevent confusion, but since I was instructed to just get something up quickly as there aren't any design specs out yet I didn't implement that.

**Comment by TheMarketingGuy** [comment]
Not sure if I'm using the correct terminology, but here I go.

It appears the main container is 1170px wide. I would consider that to be "full-width".

I think the theme is this --> https://foundationpress.olefredrik.com/

How do I use some of the functions noted here? --> https://foundationpress.olefredrik.com/kitchen-sink

**Comment by d4mation** [comment]
> How do I use some of the functions noted here? --> https://foundationpress.olefredrik.com/kitchen-sink

You're thinking like a Page Builder here. Those are all things we would need to implement for you on our end.

**Comment by TheMarketingGuy** [comment]
UHG - kind of like when I learned to play the chords on the guitar before learning individual notes...

Builder is all I have ever done + I don't know any other way = feeling like I have no control.

Is there an ETA for WP 5.0 yet? Searching, all I see a a lot of "TBD".
