### ISSUE TITLE
PHP Upgrade

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#2]
Upgrade the sonaria.com site to PHP 7.

**Comment by d4mation** [comment]
Similarly to [lowrysolutions.com](https://lowrysolutions.com), I do ~~not~~ have the ability to flip the switch for this on my own. ~~The WP Engine account holder will need to do this.~~

https://wpengine.com/support/php-7-faq/
![image](https://user-images.githubusercontent.com/7770631/36161853-bff09bc0-10b2-11e8-8791-0a4288df906a.png)

**Comment by d4mation** [comment]
I do have "Full (No Billing)" access which may meet the first requirement, but I don't believe I have access to the Support PIN. I can check on that, but I think that's reserved for the Account Owner.

**Comment by d4mation** [comment]
I do not have the ability to view the Support PIN. My guess is that that comes with "Full" Access which is different from "Full (No Billing)" I'm pretty sure.

**Comment by d4mation** [comment]
Never mind, I _do_ have access to the Support PIN. 

So I can flip the switch here for Sonaria if you'd like, @TheMarketingGuy

**Comment by d4mation** [comment]
PHP 7 Upgrade complete~ Pending IP Address change to 104.197.142.114, but that's outside this issue.
