### ISSUE TITLE
Act-On integration for Gravity Forms in Sonaria

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#3]
Please implement the ActOn integration you created for LowrySolutions.com into the Sonaria site.

The GF license has been purchased and the plugin is now active on the site.

**_Snip_** Rest is a separate Issue.

**Comment by d4mation** [comment]
@TheMarketingGuy When you get the chance, can you confirm that Act-On mapping still works on **_[http://lowrysolutions.staging.wpengine.com](http://lowrysolutions.staging.wpengine.com)_**? I separated the Act-On Mapping functionality into its own plugin to make implementing it on Sonaria easier but I want to ensure it is still working as expected.

**Comment by d4mation** [comment]
All set on https://sonaria.com and https://lowrysolutions.com :+1:
