### ISSUE TITLE
"Invisible reCAPTCHA" implementation

### ISSUE THREAD

**Issue by d4mation** [lowrysolutions/sonaria-theme-2018#4]
# Snipped from #3 

I have created an "Invisible reCAPTCHA" and that needs to be implemented too.

**_Step 1: Client side Integration:_**
**Paste this snippet before the closing </head> tag on your HTML template:**
` ` `<script src='https://www.google.com/recaptcha/api.js'></script>` ` `

**Paste this snippet at the end of the ` ` `<form>` ` ` to create a button protected by reCAPTCHA. You will need to create a callback function to handle the result.**

` ` `<button
class="g-recaptcha"
data-sitekey="6LeA1UcUAAAAALshJvbybokq1Wy1r431cEsz83Jo"
data-callback="YourOnSubmitFn">
Submit
</button>
` ` `
[The Invisible reCAPTCHA documentation site](http://g.co/recaptcha/invisibledoc) provides more details and advanced configuration options.

**_Step 2: Server side integration_**
When your users submit the form where you integrated reCAPTCHA, you'll get as part of the payload a string with the name "g-recaptcha-response". In order to check whether Google has verified that user, send a POST request with these parameters:

URL: https://www.google.com/recaptcha/api/siteverify

secret (required)           |      6LeA1UcUAAAAALthfBon0LOu08h7uDtfqpnEHvcF
response (required)      |      The value of 'g-recaptcha-response'.
remoteip                      |      The end user's ip address.

[The reCAPTCHA documentation site](https://developers.google.com/recaptcha/docs/verify) describes more details and advanced configurations.

Screen Shot:
![image](https://user-images.githubusercontent.com/24927952/36509476-e3619e02-172d-11e8-9a53-b2eba726b4d4.png)

Key Settings Screen Shot:
![image](https://user-images.githubusercontent.com/24927952/36509692-84f9a0f2-172e-11e8-8c02-cddfa4924cf7.png)

**Comment by d4mation** [comment]
@TheMarketingGuy Do you want this implemented site-wide similar to the reCAPTCHAs on lowrysolutions.com, or should this only be set for the Gravity Forms?

**Comment by d4mation** [comment]
@TheMarketingGuy: 

> I'm thinking just on Gravity Forms. I understand and appreciate the value of the reCAPTCHA but absolutely HATE when it becomes a barrier. I'm hoping the "Invisible" version is much more UX/UI friendly.

Implemented for just Gravity Forms :+1: 

Leaving for Review until it has been tested. I tested it for on Login, but having it on Login is no longer active.

**Comment by TheMarketingGuy** [comment]
Not sure how to test that since it's "invisible".

**Comment by d4mation** [comment]
I can't say for sure with Gravity Forms, but when I had it on the Login Screen it showed a little banner in the bottom right of the screen. It didn't trigger any of the ReCAPTCHA puzzles unless it thought you looked suspicious.

**Comment by d4mation** [comment]
This seems to be working as the same banner shows on the Home Page now that the Gravity Form is present. Going to close this Issue.
