### ISSUE TITLE
Implement Google Codes

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#5]
How would you like to coordinate implementation of the Google Analytics & Search Console and Bing  codes/scripts?

**Comment by d4mation** [comment]
It seems that Google Tag Manager has worked well with lowrysolutions.com, right? 

It seems like if we were to implement Google Tag Manager, then anything else could be easily added using that rather than needing any further modifications to the Theme.

**Comment by TheMarketingGuy** [comment]
Yes, I would like tag manager in there too and although Google doesn't consider having both GTM and GA codes on the site as a "best practice", I would like to have both of them.

My understanding is that there are still some data point items that GTM does not fully push over to GA for reporting.

**Comment by d4mation** [comment]
You should be able to use GTM to include the GA code, so we'd only have to implement the GTM code on our end and then the GA code can be included via GTM.

**Comment by TheMarketingGuy** [comment]
Ok. One item that I believe GTM does not report through to GA is "in-sight search". 

We'll definitely want that in Sonaria

**Comment by BigActual** [comment]
I'll double check that issue.

**Comment by TheMarketingGuy** [comment]
GTM code to implement:

**Paste this code as high in the `<head>` of the page as possible:**
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5BCRVFS');</script>
<!-- End Google Tag Manager -->
```

**Additionally, paste this code immediately after the opening `<body>` tag:**
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5BCRVFS"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by TheMarketingGuy** [comment]
GA - Global Site Tag

**Global Site Tag (gtag.js)**
This is the Global Site Tag (gtag.js) tracking code for this property. Copy and paste this code as the first item into the `<HEAD>` of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag.

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-43571502-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-43571502-4');
</script>
```

**Global Site Tag (gtag.js) and Google Tag Manager are the recommended tracking methods for new implementations. Additional implementation options are also available including analytics.js and the Measurement Protocol. Learn more about additional [tracking methods](https://support.google.com/analytics/answer/7538414).**

**Comment by d4mation** [comment]
@TheMarketingGuy I don't know if you're formatting those messages manually or not, but if you are, for code blocks you only need to put three "\`" characters at the very start and at the very end of the code block rather than per line. Also, there shouldn't be any spaces between those "\`" characters.

As well as when you type out things like `<head>`, GitHub attempts to convert those into HTML unless you place a single "\`" character on either side like I did right here.

If you click "Edit" on any of your above comments, you can see what I did to get them to display correctly :+1: It makes it easier for me to copy/paste and understand what to do (For example, since the `<head>` tag was hidden in your comment above, it made it look like it said "Copy and paste this code as the **first item of every webpage**" which isn't accurate.

**Comment by d4mation** [comment]
These are implemented and up on the site. GTM should allow inclusion of other things like Bing and I went ahead and put in the Global Site Tag into the Theme since I wasn't sure if GTM could handle that.

**Comment by TheMarketingGuy** [comment]
Site verified!
