### ISSUE TITLE
Add Act-On tracking beacon to Sonaria.com

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#7]
```
<script>/*<![CDATA[*/(function(w,a,b,d,s){w[a]=w[a]||{};w[a][b]=w[a][b]||{q:[],track:function(r,e,t){this.q.push({r:r,e:e,t:t||+new Date});}};var e=d.createElement(s);var f=d.getElementsByTagName(s)[0];e.async=1;e.src='//marketing.lowrysolutions.com/cdnr/47/acton/bn/tracker/7009';f.parentNode.insertBefore(e,f);})(window,'ActOn','Beacon',document,'script');ActOn.Beacon.track();/*]]>*/</script>
```

**Comment by d4mation** [comment]
Where does this go? On every page? With form submission?

**Comment by TheMarketingGuy** [comment]
To be honest...I'm not sure. However it was implemented for lowrysolutions.com site.

Just tried to look through the old stuff to see if there was an old issue to reference but I'm not that familiar with looking up things.

I can get you documentation if you need it.

**Comment by BigActual** [comment]
Yes, please. I don't remember if this was like the google code or if it was page specific. May need to use Tag Manager. Let' review the documentation.

**Comment by TheMarketingGuy** [comment]
Yes...looks like we used GTM to implement last time. Working on setting up google properties now.

**Comment by TheMarketingGuy** [comment]
Added Act-On beacon to GTM. Won't be able to verify until home page is build and GF form is submitted for testing.

**Comment by d4mation** [comment]
Now that the Home Page is "public" and there's a Gravity Form there, can this be verified?

**Comment by TheMarketingGuy** [comment]
Tracking has been verified. Good to close.
