### ISSUE TITLE
Slider Rev issue in IE/Edge

### ISSUE THREAD

**Issue by TheMarketingGuy** [lowrysolutions/sonaria-theme-2018#8]
The effect I'm trying to use in the slider isn't working in Edge/IE. 

I tried this --> https://www.themepunch.com/revslider-doc/problem-handlings/#fallbacks

But didn't solve the problem.

The other solution is here --> https://www.themepunch.com/faq/disable-blend-mode-ie/

But I'm not sure how it will appear.

Also - although this refers to mobile, I wonder if it can be re-purposed to work with IE/Edge.  https://www.themepunch.com/faq/hyperlink-mobile-fallback-image-5-0/

**Comment by d4mation** [comment]
The second solution sounds like it will simply disable the following Blend Modes for browsers that don't support them:

- `normal`
- `multiply`
- `screen`
- `overlay`
- `darken`
- `lighten`
- `color-dodge`
- `color-burn`
- `hard-light`
- `soft-light`
- `difference`
-  `exclusion`
- `hue`
- `saturation`
- `color`
- `luminosity`

If you need to test it to see what it would look like in an old version of Internet Explorer, Microsoft provides Virtual Machines that you can set up to view them. They have ones available from IE 8 up to Edge and you can choose which version of Windows it should run under too (Which is helpful for some _really weird_ bugs where something only doesn't work in IE 11 in Windows 7 or something like that)

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by d4mation** [comment]
Here's the caniuse page for CSS3 `mix-blend-mode` to show exactly which browsers have troubles with it: https://caniuse.com/#search=mix-blend-mode

**Comment by TheMarketingGuy** [comment]
Yep..confirmed by Slider Rev support that it won't work.

BUT there is this https://www.themepunch.com/faq/hyperlink-mobile-fallback-image-5-0/

Why can't a similar work around be made for IE/Edge?

**Comment by d4mation** [comment]
That code is some generic jQuery code that fires off when a specific element is clicked to force-redirect the web browser to another page.

That could be implemented, but if you wanted it to _only_ work for IE/Edge then some additional code to enforce that would need to be added. As it is in that example, that code should work on any browser.

**Comment by TheMarketingGuy** [comment]
Ok...well, they (Slider Rev) hasn't developed any type of solution to solve incompatibility with IE/Edge.

Any magic you think you could pull out of your hat? If not, I'll need to scrap the presentation.

I may not be saying this correctly or may have a total misconception in my thinking, but aren't there some type of user-agents or IFTTT coding that tells the website to do things under certain conditions? LIke, if browser is IE/Edge than do "this"

**Comment by d4mation** [comment]
Yep, there are ways to say "If IE/Edge, do this". That's what I was saying above.

The thing is I would need to know _what_ to do in that case. Something like making it redirect to another page on clicking it would work fine, but if it was "If IE/Edge, replace the Slider with something else entirely" like a different animation or something, things get a little tricky.

**Comment by TheMarketingGuy** [comment]
They have a a thing in the slider settings for a "fall-back" background image but the controls are only for mobile and IE8.

My thinking was "If IE/Edge - fall back to [attached image] 
![sonaria-slider-backup-background](https://user-images.githubusercontent.com/24927952/37472327-28e82304-2842-11e8-9f51-5e873847a583.png)

**Comment by d4mation** [comment]
I'll have to look at how they are doing that in their code. Ideally there will be a place for me to "hook into" to do this cleanly. Otherwise, it may attempt to load the regular version, and then have to be replaced with the fallback which would cause some "jittering".

**Comment by TheMarketingGuy** [comment]
Did you push that to a staging or live?

**Comment by d4mation** [comment]
Live. I only just got it fully working.

**Comment by TheMarketingGuy** [comment]
I can confirm that the background changed..however, nothing else is loading. Presents the same in both IE-11 and Edge as screen shot below.

![image](https://user-images.githubusercontent.com/24927952/37481416-173638ce-2858-11e8-98a0-3318b6fd1e64.png)

**Comment by TheMarketingGuy** [comment]
I could just make the fall back image the complete slide with the Sonaria logo and other text.

Might be the simplest solution.

**Comment by d4mation** [comment]
I wasn't sure if that was intentional or not. _Before_ I did anything, that's all that showed for me in IE 8 and since the feature was originally intended for IE 8, I figured that was all that should show. 

I can double check with this code disabled to see if anything else shows in IE 8 aside from the background image, but I wonder if the feature doesn't do quite what you think. I think it is meant to be a static image that _replaces_ the Slider rather than shows below the Slider as a replacement background.

--- 

Yeah, that may be simplest. I saw what it looks like in Edge without the override and it isn't pretty.

**Comment by TheMarketingGuy** [comment]
DOH....the fallback is displaying in Chrome.

**Comment by d4mation** [comment]
Isn't showing on my end. Give me a few to spin up a VM to see if it is a Windows-specific problem.

This is the downside to checking against User Agents :/ For some reason, browsers like to pretend to be each other and it ruins things.

**Comment by TheMarketingGuy** [comment]
Chrome is working again

**Comment by d4mation** [comment]
Works on my end in a Windows 10 VM with Chrome as well. 

I'll keep trying to test the IE 8 version. It is... picky. I had to enable HTTPS manually for the browser. Certainly was a different time then.

**Comment by TheMarketingGuy** [comment]
I was tinkering with these and may have caused the issue.

Take a look at these setting in the Slider Rev. You'll know more of what they do than I will.

Look here - Global Settings.
![image](https://user-images.githubusercontent.com/24927952/37482111-e1281ebc-2859-11e8-8078-51d9838b6485.png)

and here - settings for the slider
Go here first
![image](https://user-images.githubusercontent.com/24927952/37482251-48c202cc-285a-11e8-9b71-99e8257e1af3.png)

Then over on the right
![image](https://user-images.githubusercontent.com/24927952/37482290-636e19c6-285a-11e8-94b6-47c80136675b.png)

**Comment by d4mation** [comment]
From Slack:

---

> d4mation [2:16 PM]
> But, anyway, I found the limitation here.
> 
> So normally, even in IE 8, the Slider _technically_ still loads. It just simply doesn’t work in IE 8 so you don’t realize it.
> 
> If I were to force the Background Image to load in IE 11 for example, it would still show the rainbow puke everywhere because there’s nothing to say “Don’t show the crazy animations that IE 11 does not support”.
> 
> So, we can either have it show a static image instead, or the Slider may just have to lose the fancy effects altogether :confused:
> You said this solution didn’t work? https://www.themepunch.com/faq/disable-blend-mode-ie/
> Because that’s about the only way I think you _could_ disable the crazy effects without Rev Slider implementing something on their end.
> 
> Jeff at Lowry [2:20 PM]
> Ok...Well..chrome isn't working again for me
> I'm fine with the animations not showing in ALL versions of IE and Edge. I can make a static image.
> 
> d4mation [2:22 PM]
> Ok, sounds good :+1:
> 
> Should be set as-is then. I don’t know why Chrome is working then not working on your end (Can’t replicate on my end, on Mac or in a VM) but it should only trigger on IE/Edge to swap with the Background that is stored under that Fallback option.
> 
> Jeff at Lowry [2:23 PM]
> Ok...I'll generate a new background with all the graphic and text
> Do you load it or do I on my end into the Slider Rev?
> 
> d4mation [2:23 PM]
> You load it on your end in Slider Rev via that Fallback option
